# Generated by Django 5.2.17 on 2026-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedPromoPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("body", models.TextField(verbose_name="Mensaje")),
                (
                    "route",
                    models.CharField(
                        default="/", max_length=100, verbose_name="Ruta al abrir"
                    ),
                ),
                (
                    "target_specialties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Vacío = todos ("generales"). Igual semántica que Advertisement.target_specialties.',
                        verbose_name="Especialidades objetivo",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Para identificar de dónde vino en logs/admin, ej. "Anuncio: Nueva versión" o "Publicidad: Cliente X".',
                        max_length=200,
                        verbose_name="Origen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado el"
                    ),
                ),
                (
                    "sent_to_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dispositivos alcanzados"
                    ),
                ),
            ],
            options={
                "verbose_name": "Push promocional en cola",
                "verbose_name_plural": "Cola de push promocionales",
                "ordering": ["created_at"],
            },
        ),
    ]
