# Generated by Django 5.2.17 on 2026-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_queuedpromopush"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedpromopush",
            name="kind",
            field=models.CharField(
                choices=[
                    ("announcement", "Anuncio del sistema"),
                    ("advertisement", "Publicidad"),
                ],
                default="advertisement",
                help_text="announcement = siempre llega a todos, sin importar receives_advertising. advertisement = respeta el opt-out de publicidad de cada usuario.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
