# Generated by Django 5.0.14 on 2026-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0013_alter_caseprocedure_calculated_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalcase",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Si está completo, se elimina automáticamente a los 6 meses",
                null=True,
                verbose_name="Archivado el",
            ),
        ),
    ]
