# Generated by Django 5.0.14 on 2026-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0014_add_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalcase",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="N° de Factura"
            ),
        ),
    ]
