# Generated by Django 5.0.14 on 2026-06-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0026_favoriteinsurance"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favoriteinsurance",
            new_name="medico_favo_user_id_4787a7_idx",
            old_name="medico_favi_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="favoriteinsurance",
            new_name="medico_favo_insuran_5d0607_idx",
            old_name="medico_favi_ins_idx",
        ),
    ]
