# Generated by Django 5.0.14 on 2026-07-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0035_site_setting_min_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surgicalcase",
            options={
                "ordering": ["surgery_date", "-created_at"],
                "verbose_name": "Caso Quirúrgico",
                "verbose_name_plural": "Casos Quirúrgicos",
            },
        ),
        migrations.CreateModel(
            name="AnesthesiaCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cuánto vale cada unidad en quetzales",
                        max_digits=10,
                        verbose_name="Valor por Unidad (Q)",
                    ),
                ),
                (
                    "time_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Se agrega al finalizar la cirugía. Calculado: minutos / 15",
                        max_digits=8,
                        null=True,
                        verbose_name="Unidades de Tiempo",
                    ),
                ),
                (
                    "time_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duración real de la anestesia en minutos",
                        null=True,
                        verbose_name="Minutos de Anestesia",
                    ),
                ),
                (
                    "anesthesiologist_name",
                    models.CharField(
                        blank=True,
                        help_text="Texto libre si no es un colega registrado",
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Anestesiólogo",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anesthesiologist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Colega registrado en el sistema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anesthesia_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Anestesiólogo (Colega)",
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anesthesia",
                        to="medico.surgicalcase",
                        verbose_name="Caso Quirúrgico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anestesia",
                "verbose_name_plural": "Anestesias",
            },
        ),
        migrations.CreateModel(
            name="AnesthesiaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surgery_code",
                    models.CharField(max_length=50, verbose_name="Código"),
                ),
                (
                    "surgery_name",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "base_units",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Unidades Base"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anesthesia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="medico.anesthesiacase",
                        verbose_name="Sesión de Anestesia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código Anestesia",
                "verbose_name_plural": "Códigos Anestesia",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
