# Generated by Django 5.0.14 on 2026-07-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0036_add_anesthesia_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="anesthesiacase",
            name="anesthesiologist_accepted",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="null=pendiente, true=aceptó, false=rechazó",
                null=True,
                verbose_name="Anestesiólogo Aceptó",
            ),
        ),
    ]
