# Generated by Django 5.0.14 on 2026-07-28 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0047_surgicalcase_assistant_status_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("assistant", "Médico Ayudante"),
                            ("anesthesiologist", "Anestesiólogo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborator_removals",
                        to="medico.surgicalcase",
                    ),
                ),
                (
                    "removed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborator_removals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remoción de colaborador",
                "verbose_name_plural": "Remociones de colaboradores",
                "unique_together": {("case", "removed_user", "role")},
            },
        ),
    ]
