# Generated by Django 5.0.14 on 2026-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0049_add_operated_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalcase",
            name="anesthesiologist_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca que ya se envió el recordatorio push al anestesiólogo invitado, según sus propias horas de anticipación",
                null=True,
                verbose_name="Recordatorio de cirugía enviado al anestesiólogo el",
            ),
        ),
        migrations.AddField(
            model_name="surgicalcase",
            name="assistant_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca que ya se envió el recordatorio push al médico ayudante, según sus propias horas de anticipación",
                null=True,
                verbose_name="Recordatorio de cirugía enviado al ayudante el",
            ),
        ),
        migrations.AlterField(
            model_name="surgicalcase",
            name="surgery_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca que ya se envió el recordatorio push al médico principal para esta cirugía",
                null=True,
                verbose_name="Recordatorio de cirugía enviado el",
            ),
        ),
    ]
