# Generated by Django 5.0.14 on 2026-08-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0050_surgicalcase_anesthesiologist_reminder_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalcase",
            name="anesthesiologist_operated_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca que ya se envió el recordatorio al anestesiólogo de marcar como operada su parte",
                null=True,
                verbose_name="Recordatorio de operado enviado al anestesiólogo el",
            ),
        ),
        migrations.AddField(
            model_name="surgicalcase",
            name="assistant_operated_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca que ya se envió el recordatorio al ayudante de marcar como operada su parte",
                null=True,
                verbose_name="Recordatorio de operado enviado al ayudante el",
            ),
        ),
    ]
