# Generated by Django 5.0.14 on 2026-08-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medico",
            "0051_surgicalcase_anesthesiologist_operated_reminder_sent_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatsTotals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_cases", models.PositiveIntegerField(default=0)),
                (
                    "total_rvu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_totals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Totales históricos de usuario",
                "verbose_name_plural": "Totales históricos de usuario",
            },
        ),
        migrations.CreateModel(
            name="PurgedHospitalStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_count", models.PositiveIntegerField(default=0)),
                (
                    "total_rvu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purged_stats",
                        to="medico.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purged_hospital_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de hospital purgada",
                "verbose_name_plural": "Estadísticas de hospital purgadas",
                "unique_together": {("user", "hospital")},
            },
        ),
        migrations.CreateModel(
            name="PurgedInsuranceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_count", models.PositiveIntegerField(default=0)),
                (
                    "total_rvu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purged_stats",
                        to="medico.insurancecompany",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purged_insurance_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de aseguradora purgada",
                "verbose_name_plural": "Estadísticas de aseguradora purgadas",
                "unique_together": {("user", "insurance")},
            },
        ),
        migrations.CreateModel(
            name="PurgedProcedureStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgery_code", models.CharField(max_length=50)),
                (
                    "surgery_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("specialty", models.CharField(blank=True, max_length=100, null=True)),
                ("procedure_count", models.PositiveIntegerField(default=0)),
                (
                    "total_rvu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purged_procedure_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de procedimiento purgada",
                "verbose_name_plural": "Estadísticas de procedimiento purgadas",
                "unique_together": {("user", "surgery_code")},
            },
        ),
    ]
