# Generated by Django 5.0.14 on 2026-08-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0052_userstatstotals_purgedhospitalstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalcase",
            name="anesthesiologist_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuándo se notificó al anestesiólogo invitado sobre este caso",
                null=True,
                verbose_name="Fecha de Notificación al Anestesiólogo",
            ),
        ),
    ]
