# Generated by Django 5.0.14 on 2026-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0005_friendrequest_friendship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Envío del Token de Reset"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Token de Reseteo de Contraseña",
            ),
        ),
    ]
