# Generated by Django 5.0.14 on 2026-08-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0019_apple_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="surgery_reminder_hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Horas antes de la cirugía para enviar recordatorio push",
                verbose_name="Horas de recordatorio de cirugía",
            ),
        ),
    ]
