# Generated by Django 5.0.14 on 2026-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0020_alter_customuser_surgery_reminder_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ls_payment_failed_downgrade",
            field=models.BooleanField(
                default=False,
                help_text="True si se lo bajó a Free por falta de pago (no por cancelación manual). Se muestra en Settings.",
                verbose_name="Bajado a Free por pago rechazado",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ls_payment_overdue_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha desde la que la renovación del pago está vencida (pago rechazado o webhook de vencimiento perdido). Si pasan más de 3 días, se baja a Free.",
                null=True,
                verbose_name="Vencido desde",
            ),
        ),
    ]
