# Generated by Django 5.2.17 on 2026-08-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0021_customuser_ls_payment_failed_downgrade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="trial_ending_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Guarda el trial_ends_at vigente cuando se mandó el email de 'tu prueba termina en 3 días' (no el momento del envío) — así, si trial_ends_at se corre más adelante (referidos, fin de promo), deja de coincidir y el recordatorio se vuelve a enviar automáticamente para la nueva fecha.",
                null=True,
                verbose_name="Recordatorio de fin de prueba enviado para",
            ),
        ),
    ]
