# Generated by Django 5.2.17 on 2026-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0022_trial_ending_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="inactivity_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Guarda el last_active_at vigente cuando se mandó el push de 'volvé a la app' — así, si el usuario vuelve a abrir la app, last_active_at avanza y deja de coincidir, permitiendo que se le mande otro recordatorio la próxima vez que esté inactivo.",
                null=True,
                verbose_name="Recordatorio de inactividad enviado para",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_active_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Se actualiza cada vez que la app carga el perfil del usuario (GET /profile), es decir, cada apertura de la app — no solo el login, ya que la sesión se mantiene activa por tiempo indefinido vía refresh token.",
                null=True,
                verbose_name="Última actividad",
            ),
        ),
    ]
