# Generated by Django 5.2.17 on 2026-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0023_customuser_inactivity_reminder_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="inactivity_reminder_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cuántos push de inactividad lleva enviados sin que el usuario haya vuelto a abrir la app — define el próximo intervalo (20h, luego 3 días, luego cada 5 días). Se reinicia solo cuando el usuario vuelve a estar activo y luego vuelve a quedar inactivo.",
                verbose_name="Recordatorios de inactividad enviados en esta racha",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="inactivity_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento en que se mandó el último push de 'volvé a la app' de la racha de inactividad actual. Si last_active_at avanza más allá de este valor (el usuario volvió a abrir la app), la racha se considera terminada y el conteo/escalonado arrancan de cero.",
                null=True,
                verbose_name="Último recordatorio de inactividad enviado",
            ),
        ),
    ]
