# Generated by Django 5.2.17 on 2026-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0024_customuser_inactivity_reminder_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="receives_announcements",
            field=models.BooleanField(
                default=True,
                help_text="Push promocionales (Anuncios del sistema, publicidad de clientes). Solo un usuario con acceso Premium puede desactivarlo — se valida en el serializer, no solo en el frontend. El resto de las notificaciones (colegas, cirugías, referidos) no pasan por este campo y siempre se envían.",
                verbose_name="Recibe novedades y anuncios",
            ),
        ),
    ]
