# Generated by Django 5.2.17 on 2026-08-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0025_customuser_receives_announcements"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="receives_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Push de cirugías próximas, casos marcados como operados, invitaciones de colegas/casos sin responder, y acciones del equipo en un caso — todo lo que pasa por notify_user/notify_team (apps/medico/services/firebase.py). Libre para cualquier plan, a diferencia de receives_announcements.",
                verbose_name="Recibe recordatorios y solicitudes",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="receives_announcements",
            field=models.BooleanField(
                default=True,
                help_text="Push promocionales (Anuncios del sistema, publicidad de clientes plan oro) — ver apps/communication/services/promo_push.py. Solo un usuario con acceso Premium puede desactivarlo — se valida en el serializer, no solo en el frontend. Totalmente independiente de receives_reminders: son dos canales distintos.",
                verbose_name="Recibe novedades y anuncios",
            ),
        ),
    ]
