# Generated by Django 5.2.17 on 2026-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medio_auth", "0026_customuser_receives_reminders_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="receives_announcements",
        ),
        migrations.AddField(
            model_name="customuser",
            name="receives_advertising",
            field=models.BooleanField(
                default=True,
                help_text="Solo publicidad de clientes plan oro (ver apps/communication/services/promo_push.py, kind='advertisement'). Los Anuncios del sistema (kind='announcement' — versión nueva, avisos importantes) NO pasan por este campo, siempre llegan a todos igual que las notificaciones de cirugías/colegas. Solo un usuario con acceso Premium puede desactivarlo — se valida en el serializer, no solo en el frontend.",
                verbose_name="Recibe publicidad",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="receives_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Push de cirugías próximas, casos marcados como operados, invitaciones de colegas/casos sin responder, y acciones del equipo en un caso — todo lo que pasa por notify_user/notify_team (apps/medico/services/firebase.py). Libre para cualquier plan, a diferencia de receives_advertising.",
                verbose_name="Recibe recordatorios y solicitudes",
            ),
        ),
    ]
