# Generated by Django 5.0.14 on 2026-05-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0005_add_category_to_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("congreso", "Congreso"),
                    ("casa_medica", "Casa Médica"),
                    ("hospital", "Hospital"),
                    ("tecnologia", "Tecnología Médica"),
                    ("farmaceutica", "Farmacéutica"),
                    ("educacion", "Educación Médica"),
                    ("clinica", "Clínica"),
                ],
                default="general",
                help_text="Categoría temática para el feed de Novedades",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
    ]
